version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/flask_sns
      - SECRET_KEY=${SECRET_KEY}
      - MAIL_DEBUG=true
      # Resend設定
      - USE_RESEND=${USE_RESEND:-true}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - RESEND_FROM_EMAIL=${RESEND_FROM_EMAIL:-onboarding@resend.dev}
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=flask_sns
    ports:
      - "5432:5432"

volumes:
  postgres_data:
